language: R
cache: packages

addons:
  apt:
    packages:
      - libmagick++-dev

matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov(type=c("tests", "vignettes", "examples"))'
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
      on:
        branch: master
