#' Strategy Unit Theme Palettes
#'
#' This function returns a palette generated by colorRampPalette from one of the
#' Strategy Unit palettes
#'
#' @param palette The name of palette to use
#' @param reverse Optional: boolean value to reverse the palette
#' @param ... arguments to pass to colorRamp
#'
#' @importFrom grDevices colorRampPalette
#'
#' @return
#' @export
#'
#' @examples
#' su_theme_pal()
#' # or, specify a paltte
#' su_theme_pal("oranges")
#' # a reverse palette
#' su_theme_pal("slates", TRUE)
su_theme_pal <- function(palette = su_theme_palettes, reverse = FALSE, ...) {
  palette <- match.arg(palette)

  pal <- su_theme_cols(palette = palette)

  if (reverse) pal <- rev(pal)

  grDevices::colorRampPalette(pal, ...)
}
